-- ============================================================================
-- 06-journal-additions.sql — On-This-Day + manual-entry original-text preservation
-- ----------------------------------------------------------------------------
-- These additions layer onto the CORE `journal` table (defined in
-- 01-core-entities.sql). They are ADDITIVE: every column here is created on the
-- core regen's `journal` CREATE, and added to an existing `journal` table by
-- install-extensions.py via ALTER TABLE ADD COLUMN. Old rows get NULL; the UI
-- treats NULL exactly as the documented default.
--
-- TWO FEATURES BACKED HERE:
--
-- (A) ON THIS DAY — the Hub shows journal entries from the SAME calendar day in
--     prior periods (1 month ago, 6 months ago, then every prior year). The
--     `journal` table already carries `entry_date` (ISO YYYY-MM-DD), `title`,
--     `content`, `slug`, `file_path`, and `journal_media` already links embedded
--     images per entry. The only thing missing for performance is an index on
--     the date column the module filters by — added below. The exact query
--     pattern is in DATA-CONTRACT.md §9 (it is PARAMETERIZED on "today", so it
--     is a server/module query, NOT a view — a view cannot take the today param).
--
-- (B) MANUAL-ENTRY ORIGINAL TEXT + INTEGRATION STATUS — when the user adds a
--     journal entry by hand in the cockpit and later has Penn integrate/rewrite
--     it, the ORIGINAL text must be preserved so the cockpit can show an
--     "unfold original". Two columns carry this:
--
--       original_body       the user's verbatim original text. Set ONCE, when
--                           Penn first rewrites a raw entry: Penn copies the
--                           current body into original_body, then rewrites the
--                           body. NULL means "never integrated — body IS the
--                           original" (nothing to unfold).
--       integration_status  'raw'        — user-entered, not yet integrated
--                           'integrated' — Penn has rewritten; original_body set
--                           NULL is treated as 'raw' for legacy/auto-captured
--                           entries (Penn-authored-from-the-start entries can be
--                           written straight to 'integrated' with no original).
--
--     Frontmatter contract (DATA-CONTRACT.md §10):
--       manually_added: true            (the entry came from the cockpit's manual
--                                        add flow, not Penn's capture pipeline)
--       integration_status: raw|integrated
--       original_body: |                (block scalar — preserved verbatim;
--         <the user's original words>    set by Penn at integration time)
--
--     The UI reads integration_status to decide whether to show the "unfold
--     original" affordance, and reads original_body for what to reveal.
-- ============================================================================

-- (B) Manual-entry preservation columns. Idempotent: only ADD when absent (the
-- installer guards with PRAGMA table_info; the core regen's CREATE includes them
-- from the start). manually_added stored as INTEGER (SQLite has no native bool).
ALTER TABLE journal ADD COLUMN original_body TEXT;
ALTER TABLE journal ADD COLUMN integration_status TEXT;
ALTER TABLE journal ADD COLUMN manually_added INTEGER;

-- (A) On-This-Day performance index. The module filters journal by
-- substr(entry_date, 6, 5) = '<MM-DD>' across many candidate dates. An index on
-- entry_date lets SQLite range-scan the date column instead of full-scanning the
-- (potentially years-deep) journal. The module builds explicit candidate dates
-- (see DATA-CONTRACT.md §9) and queries entry_date = <date> per period, which
-- this index serves directly.
CREATE INDEX IF NOT EXISTS idx_journal_entry_date ON journal (entry_date);
