-- ============================================================================
-- mypka-cockpit.db  —  cockpit-owned, READ-WRITE, NOT part of the mypka.db regen.
-- Migration 007: per-module display ORDER for the Hub (Settings reorder).
--
-- Additive only, exactly like 006: this brings the cockpit-local module_prefs
-- table up to schema_version 7 by adding a sort_order column. Zero contact with
-- canonical markdown, mypka.db, GL-002, templates, or regen-mypka-db.py.
--
-- WHY A COLUMN (not a new table): a Hub module's order is one more PER-MODULE
-- runtime UI preference, sitting right next to `enabled` — same lifecycle (local,
-- disposable, default-derived). Co-locating it in module_prefs keeps one UPSERT
-- path and one default-fill rule (cockpitSettingsDb.js).
--
-- DEFAULT POSTURE: a module with NO row has NO explicit position. The data layer
-- (getModulePrefs) fills the gap from the KNOWN_MODULES catalogue order — exactly
-- the same default-derivation it already does for `enabled` (missing row = ON).
-- So a fresh cockpit, or any module the user has never reordered, renders in the
-- canonical catalogue order. The sentinel default here is -1 ("unset"); the data
-- layer treats any row whose sort_order < 0 as "fall back to catalogue index".
--
-- SQLite note: ALTER TABLE ... ADD COLUMN is the only safe additive DDL here, and
-- it is NOT idempotent on its own (re-adding an existing column throws). The boot
-- runner already guarantees idempotency: a migration file only runs when its
-- leading version (7) is strictly greater than the DB's recorded schema_version,
-- so this statement executes at most once per database. (006 used IF NOT EXISTS
-- because CREATE TABLE supports it; ADD COLUMN does not, and does not need it
-- under the version-gated runner.)
-- ============================================================================

ALTER TABLE module_prefs ADD COLUMN sort_order INTEGER NOT NULL DEFAULT -1;
